version: 2

sources:
  - name: raw
    database: ADEBNEYDEMODB2
    schema: RAW
    tables:
      - name: orders
        identifier: RAW_ORDERS
      - name: customers
        identifier: RAW_CUSTOMERS
      - name: products
        identifier: RAW_PRODUCTS
      - name: order_items
        identifier: RAW_ORDER_ITEMS

